### ISSUE TITLE
수행결과입니다.

### ISSUE THREAD

**Issue by di9manse** [ShineSoYoung/CRA#47]
![image](https://user-images.githubusercontent.com/94810880/161522405-1dc94b2f-f065-4526-9055-2db373bc30b6.png)

최신 Trunk기준으로 다음과 같은 Debug Assert가 발생합니다.

Vector를 사용하실때 탐색 중, 삭제를 하는 경우에 위와 같은 Assert가 발생하는 경우가 있습니다.

혹시 해당 경우인지 살펴봐 주시기 바랍니다.

**Comment by BulgogiBake** [comment]
디버깅에서는 txt 파일의 맨 앞의 문장 CMD가 깨져서 발생하는 오류입니다. 현재 들어가 있는 input file들이 utf8 bom 인코딩이 되어있는데 앞의 글자가 포맷 헤더여서 발생하는 문제입니다. 
혹시 sln파일을 여셨나요? sln 파일과 같이 들어있는 .editorconfig파일이 visual studio에서 편집되는 모든 txt를 저렇게 인코딩을 하게 해두었는게 문제가 되었네요. ㅠㅜ 최신 release에서 이 파일을 빼두었으니 비주얼 스튜디오를 모두 끄시고 시도하시면 될것 같습니다. 혹은 현재 input파일을 메모장으로 ANSI 저장하면 될 것 같습니다.

**Comment by di9manse** [comment]
8f5bcca 으로 수행한 결과입니다. 아마 말씀하신 것 까지 반영해서 제가 테스트 한 것 같습니다.
위 불량 분석을 참고하셔서 TDD 부탁드립니다.

**Comment by BulgogiBake** [comment]
input data의 마지막 줄 개행을 CMD 처리하는 버그가 있었습니다. 해결하고 업로드 하겠습니다.
