### ISSUE TITLE
Fail 시나리오 공유드립니다.

### ISSUE THREAD

**Issue by di9manse** [ShineSoYoung/CRA#54]
expected
MOD,09123597,KVAXH CC,CL3,010-6361-8374,19780907,ADV

actual
MOD,NONE

시나리오
ADD, , , ,09123597,KVAXH CC,CL3,010-6361-8374,19780907,ADV
MOD,-p,-l, ,name,CC,phoneNum,010-6350-3766

**Comment by answkcse11** [comment]
release v3 에서 개선여부 확인하였습니다!
